# Generated by Django 5.1.6 on 2025-05-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='facturas_excel/')),
                ('nombre', models.CharField(max_length=200)),
                ('rutaAlmacenamiento', models.CharField(max_length=200)),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoProcesamiento', models.CharField(choices=[('PAG', 'Pagado'), ('PEN', 'Pendiente')], max_length=50)),
                ('fechasubida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
