# Generated by Django 5.2 on 2025-05-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0002_detallefactura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='peso',
            new_name='peso_kg',
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='unidades',
            new_name='unidades_fisicas',
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='valor',
            new_name='valor_fob',
        ),
    ]
