# Generated by Django 5.2 on 2025-05-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='facturas_excel/')),
                ('nombre', models.CharField(max_length=200)),
                ('rutaAlmacenamiento', models.CharField(max_length=200)),
                ('tamaño', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoProcesamiento', models.CharField(choices=[('PAG', 'Pagado'), ('PEN', 'Pendiente')], max_length=50)),
                ('fechasubida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignatario', models.CharField(max_length=200, verbose_name='Nombres y Apellidos')),
                ('ruc_cedula', models.CharField(max_length=20, verbose_name='RUC / Cédula')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (kg)')),
                ('valor_fob', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor USD')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción del Producto')),
                ('unidades_fisicas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidades')),
                ('factura_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Factura Comercial')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ARCHIVOS.factura')),
            ],
        ),
    ]
